### PR TITLE
Fix Events Matching

### LINKED ISSUE #477: Event matching by name is not robust
#468 introduced matching by name, should match by the id of the events that gcal returns, can possibly set as mongo id as well.

Matching by name not robust b/c multiple events can be named the same (eg. Dinner)

### PR DESCRIPTION
**Pull request by slowjazz**
Fixes #477 

### Overview
After pulling events from Google Calendar, use the `uid` field which is like a unique Google Calendar event object ID to match with events in the database. 
It is now possible to call the `addOrUpdateEvent` resolver to add or update an event with either an ObjectID or a google calendar ID (`gcalID`). However, either must be required or an error is thrown. If both are provided, the google calendar ID is used as the matcher. 

### Data model changes
- entity Event: Add 'gcalID' string field. Optional. 
- interface EventUpdate: Add 'gcalID' and 'id' string fields. Both optional.
- input EventUpdateInput: Add 'gcalID' and 'id' string fields. Both optional.

### Function changes
- `addOrUpdateEvent` will perform add or update given an EventUpdate that contain represent a transformed event from GCal or an event queried from the DB.

### Tests
- Tests added for adding/updating an event using an update with an ObjectID
- Test added for adding/updating event with no GCalID or id.

### CODE REVIEW

File: src/server/events/index.ts [hunk 1]
```diff
@@ -97,12 +91,13 @@ export async function addOrUpdateEvent(
 		description: eventInput.description,
 		location: eventInput.location,
 		eventType: eventInput.eventType,
+		gcalID: eventInput.gcalID,
 	} as EventDbObject;
-
 	const { value, lastErrorObject, ok } = await models.Events.findOneAndUpdate(
-		{ name: eventDiffObj.name },
+		eventDiffObj.gcalID ? { gcalID: eventDiffObj.gcalID } : { _id: eventDiffObj._id },
```
Comment (cktang88) [inline src/server/events/index.ts]: so basically, if the input gives a gcalID, you find by gcalID, otherwise, you find by mongoDB id?

Comment (cktang88) [reply src/server/events/index.ts]: why would an input not have a gcal id?

Comment (slowjazz) [reply src/server/events/index.ts]: Yes, an input may not have a gcal id if you're trying to construct an event without pulling from gcal i.e. some events table UI; constructing obscure internal events not for public use
